#!/usr/bin/env bash
# schema/regen.sh — regenerate schema/schema.sql
#
# Two strategies, picked automatically:
#
#   1. If DATABASE_URL is set, run schema_dump.py (live introspection — best path)
#   2. Otherwise, fall back to concatenating migrations/*.sql (build-time history,
#      good but won't capture pre-baseline tables until you set DATABASE_URL once)
#
# Run from the project root:
#   bash schema/regen.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCHEMA_DIR="$ROOT/schema"
MIGRATIONS_DIR="$ROOT/migrations"
OUT="$SCHEMA_DIR/schema.sql"

if [[ -n "${DATABASE_URL:-}" ]]; then
  echo "DATABASE_URL set → introspecting live database via schema_dump.py"
  python "$ROOT/schema_dump.py" > "$OUT"
  echo "✓ Wrote $OUT (live snapshot)"
else
  echo "DATABASE_URL unset → concatenating migrations/*.sql as fallback"
  echo "  (set DATABASE_URL for a real pg_dump-style snapshot)"

  cat > "$OUT" <<EOF
-- schema.sql
-- Auto-generated by schema/regen.sh (migrations-concat fallback mode)
-- Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
-- DO NOT EDIT BY HAND. Re-run schema/regen.sh after schema changes.
--
-- This is the FALLBACK output (DATABASE_URL was not set when regen ran).
-- It captures every migration in chronological order, but does NOT include
-- the pre-baseline tables that exist only in the live Supabase project.
--
-- For a complete snapshot (all tables including pre-baseline):
--   1. Get the Postgres connection string from Supabase Dashboard →
--      Settings → Database → Connection string → URI.
--   2. Export it: export DATABASE_URL="postgres://…"
--   3. Re-run: bash schema/regen.sh
--

EOF

  count=0
  for m in "$MIGRATIONS_DIR"/*.sql; do
    [[ -f "$m" ]] || continue
    name=$(basename "$m")
    {
      echo ""
      echo "-- ─── $name ─────────────────────────────────────────────"
      echo ""
      cat "$m"
    } >> "$OUT"
    count=$((count + 1))
  done

  echo "✓ Wrote $OUT (concat of $count migrations)"
fi
