# schema/regen.ps1 — regenerate schema/schema.sql
#
# Two strategies, picked automatically:
#
#   1. If DATABASE_URL is set, run schema_dump.py (live introspection — best path)
#   2. Otherwise, fall back to concatenating migrations/*.sql (build-time history,
#      good but won't capture pre-baseline tables until you set DATABASE_URL once)
#
# Run from the project root:
#   pwsh schema/regen.ps1

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$schemaDir = Join-Path $root "schema"
$migrationsDir = Join-Path $root "migrations"
$outFile = Join-Path $schemaDir "schema.sql"

if ($env:DATABASE_URL) {
  Write-Host "DATABASE_URL set → introspecting live database via schema_dump.py" -ForegroundColor Cyan
  python (Join-Path $root "schema_dump.py") | Out-File -FilePath $outFile -Encoding utf8
  Write-Host "✓ Wrote $outFile (live snapshot)" -ForegroundColor Green
} else {
  Write-Host "DATABASE_URL unset → concatenating migrations/*.sql as fallback" -ForegroundColor Yellow
  Write-Host "  (set DATABASE_URL for a real pg_dump-style snapshot)" -ForegroundColor Yellow

  $header = @"
-- schema.sql
-- Auto-generated by schema/regen.ps1 (migrations-concat fallback mode)
-- Generated at: $(Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
-- DO NOT EDIT BY HAND. Re-run schema/regen.ps1 after schema changes.
--
-- This is the FALLBACK output (DATABASE_URL was not set when regen ran).
-- It captures every migration in chronological order, but does NOT include
-- the pre-baseline tables that exist only in the live Supabase project.
--
-- For a complete snapshot (all tables including pre-baseline):
--   1. Get the Postgres connection string from Supabase Dashboard →
--      Settings → Database → Connection string → URI.
--   2. Set it: `$env:DATABASE_URL = "postgres://…"`
--   3. Re-run: pwsh schema/regen.ps1
--

"@
  $header | Out-File -FilePath $outFile -Encoding utf8

  $migrations = Get-ChildItem -Path $migrationsDir -Filter "*.sql" | Sort-Object Name
  foreach ($m in $migrations) {
    "`n-- ─── $($m.Name) ─────────────────────────────────────────────`n" | Out-File -FilePath $outFile -Encoding utf8 -Append
    Get-Content $m.FullName | Out-File -FilePath $outFile -Encoding utf8 -Append
  }

  Write-Host "✓ Wrote $outFile (concat of $($migrations.Count) migrations)" -ForegroundColor Green
}
