-- schema.sql
-- Auto-generated by schema/regen.sh (migrations-concat fallback mode)
-- Generated at: 2026-05-11T01:54:34Z
-- DO NOT EDIT BY HAND. Re-run schema/regen.sh after schema changes.
--
-- This is the FALLBACK output (DATABASE_URL was not set when regen ran).
-- It captures every migration in chronological order, but does NOT include
-- the pre-baseline tables that exist only in the live Supabase project.
--
-- For a complete snapshot (all tables including pre-baseline):
--   1. Get the Postgres connection string from Supabase Dashboard →
--      Settings → Database → Connection string → URI.
--   2. Export it: export DATABASE_URL="postgres://…"
--   3. Re-run: bash schema/regen.sh
--


-- ─── 0001_baseline_2026-05-08.sql ─────────────────────────────────────────────

-- 0001_baseline_2026-05-08.sql
--
-- Baseline marker for the migration system. No DDL.
--
-- All schema in the Supabase project as of 2026-05-08 was applied directly
-- via the Supabase SQL editor or supabase-py inserts, with no version control
-- record. This file establishes the starting point: from here forward, every
-- schema change lives in this folder before it lives in production.
--
-- The pre-baseline tables (treasury_companies, confirmed_purchases,
-- pending_purchases, confirmed_sales, edgar_filings, subscribers,
-- leaderboard_snapshots, etc.) are NOT defined here. To recreate them in a
-- fresh environment, currently you must either:
--   (a) restore from a Supabase backup, or
--   (b) connect to the live DB and run pg_dump --schema-only.
--
-- A future phase 3b migration will replace this marker with the full
-- pg_dump of the baseline schema, making the project reproducible from
-- scratch. Until then, this file's only job is to anchor the version chain.

DO $$ BEGIN
  RAISE NOTICE 'Baseline migration 0001 applied — schema versioning starts here';
END $$;

-- ─── 0002_add_edgar_filings_source.sql ─────────────────────────────────────────────

-- 0002_add_edgar_filings_source.sql
--
-- Add the `source` column to edgar_filings.
--
-- Background: global_filing_scanner.py and edgar_realtime.py adapters all
-- include a 'source' field in their upsert payloads (e.g., 'SEC EDGAR (USA)',
-- 'Google News [ja-JP]', 'CoinDesk'). The column was missing from the table
-- schema for 28+ days, causing every upsert from those paths to fail silently
-- (the exception was swallowed by `logger.debug`). edgar_filings was empty
-- as a result; only news/atom paths surfaced filings, and only after the
-- column was added.
--
-- This ALTER was applied manually to the live Supabase on 2026-05-08 via the
-- SQL editor. This file captures that change so it's reproducible. Idempotent
-- via IF NOT EXISTS, so re-running against the live DB is a no-op.

ALTER TABLE edgar_filings ADD COLUMN IF NOT EXISTS source TEXT;

-- ─── 0003_add_data_freshness.sql ─────────────────────────────────────────────

-- 0003_add_data_freshness.sql
--
-- Create the `data_freshness` table referenced by freshness_tracker.py.
--
-- The SETUP_SQL constant at freshness_tracker.py:484-499 has lived as a
-- docstring asking the operator to "run this in your Supabase SQL Editor".
-- Whether it was actually applied is unknown until you run this migration:
-- if the table already exists, IF NOT EXISTS makes this a no-op; if it
-- doesn't, this migration creates it.
--
-- The table powers the data-freshness widget on the dashboard (freshness
-- per source, with ages and last-error). save_to_supabase() upserts here
-- on every scan cycle.

CREATE TABLE IF NOT EXISTS data_freshness (
    id BIGSERIAL PRIMARY KEY,
    snapshot_time TIMESTAMP WITH TIME ZONE UNIQUE NOT NULL,
    overall_health TEXT DEFAULT 'unknown',
    live_count INTEGER DEFAULT 0,
    stale_count INTEGER DEFAULT 0,
    unavailable_count INTEGER DEFAULT 0,
    sources_json JSONB DEFAULT '[]'::jsonb,
    provenance_json JSONB DEFAULT '{}'::jsonb
);

-- ─── 0004_add_last_seen_in_source.sql ─────────────────────────────────────────────

-- 0004_add_last_seen_in_source.sql
--
-- Add `last_seen_in_source` column to treasury_companies for stale-entity
-- detection.
--
-- Background: after step 8 of the architectural roadmap (replacing
-- treasury_sync's wipe-and-rewrite with field-preserving upserts), entities
-- that disappear from CoinGecko + BitcoinTreasuries.net retain their
-- last-known state in the DB instead of being deleted. The existing
-- `last_updated` column doesn't distinguish "fresh from source" from
-- "merely touched by sync" because every upsert sets it to NOW() regardless
-- of whether the entity actually appeared in source data this cycle.
--
-- This new column tracks the latter — it's only set when an entity is
-- actually upserted from source data (CoinGecko/BT). After the change to
-- _upsert_entities lands, entities not present in a source stop getting
-- their last_seen_in_source updated. _prune_stale_entities then deletes
-- rows where last_seen_in_source < 30 days ago AND btc_holdings = 0
-- (conservative — only prunes empty entities, never destroys BTC history).
--
-- Backfill: existing rows get last_seen_in_source = last_updated (proxy for
-- "this was touched recently") so they aren't immediately marked stale on
-- the next sync. New rows get NULL until the next upsert sets it.

ALTER TABLE treasury_companies ADD COLUMN IF NOT EXISTS last_seen_in_source TIMESTAMPTZ;

-- Idempotent backfill: COALESCE so re-running doesn't overwrite values
-- that the application has already set.
UPDATE treasury_companies
SET last_seen_in_source = COALESCE(last_seen_in_source, last_updated, NOW());

-- ─── 0005_saved_views.sql ─────────────────────────────────────────────

-- 0005_saved_views.sql
--
-- Per-user (and optionally team-shared) saved views for filterable pages.
--
-- Background: power users on the Team plan re-apply the same filter set
-- every visit (e.g. "miners with BTC > 1k", "EU public companies sorted by
-- adoption velocity"). Without persistence the product is a viewer, not a
-- workspace. Saved views are the bridge.
--
-- Schema design:
--   user_id    — owner of the view (always set, even for team-shared views)
--   team_id    — when null, the view is private to user_id
--                when set, the view is visible to every member of team_id
--                The 'Share with team' toggle in the UI flips this.
--                Forward-compatible with the upcoming teams table; today no
--                team rows exist yet, so all views are effectively per-user.
--   page       — short string identifying the surface ('leaderboard',
--                'research', 'purchases', 'regulatory', 'competitive', etc.)
--                Indexed alongside user_id and team_id for fast lookups.
--   name       — user-facing label ('My EU shortlist', 'Big Q4 buyers')
--   filters    — JSONB blob of the filter state. Schema is page-specific;
--                we do not enforce a structure here so each page can evolve
--                its filter shape independently.
--
-- Row-level access control:
--   Read: a row is visible to user_id, OR to anyone whose subscriber row
--         has team_id matching the view's team_id (RLS to be wired when
--         teams ship; for now Supabase service-role key is used).
--   Write: only user_id may UPDATE/DELETE their views.
--
-- Cascade behavior: dropping a subscriber will leave dangling saved_views
-- rows, but they're harmless — readers filter by the current user_id.

CREATE TABLE IF NOT EXISTS user_saved_views (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     TEXT NOT NULL,
  team_id     TEXT,
  page        TEXT NOT NULL,
  name        TEXT NOT NULL,
  filters     JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Hot path: "show me this user's saved views for /leaderboard"
CREATE INDEX IF NOT EXISTS idx_saved_views_user_page
  ON user_saved_views (user_id, page);

-- Hot path: "show me every saved view shared with this team for /leaderboard"
-- Partial index keeps it small — team_id is null on the majority of rows.
CREATE INDEX IF NOT EXISTS idx_saved_views_team_page
  ON user_saved_views (team_id, page)
  WHERE team_id IS NOT NULL;

-- ─── 0006_audit_log.sql ─────────────────────────────────────────────

-- 0006_audit_log.sql
--
-- Append-only audit log of meaningful mutations across the product.
--
-- Background: Enterprise procurement and compliance teams ask "who changed
-- what, when?" before signing. Without an audit trail this question can't be
-- answered, full stop. This table is the source of truth.
--
-- Scope (this migration): mutations only. We capture profile updates,
-- watchlist changes, plan changes (from Stripe webhooks), saved-view
-- create/update/delete, and account deletion. We deliberately do NOT capture
-- page views or read-only API hits — those are noise, blow past Supabase's
-- free tier within weeks at any scale, and are not what compliance asks
-- about. Enterprise customers requesting full read-trail will need a
-- second migration that pipes API access logs into a separate table or
-- ships them to a SIEM.
--
-- Schema design:
--   actor_email   — email at the time of the action (denormalized so the
--                   row is interpretable even if the subscriber is later
--                   deleted)
--   actor_id      — subscriber_id at the time of the action (also
--                   denormalized for the same reason)
--   action        — short dotted slug describing the action ('profile.update',
--                   'watchlist.add', 'watchlist.remove', 'plan.upgrade',
--                   'plan.downgrade', 'saved_view.create', 'account.delete',
--                   etc.)
--   entity_type   — kind of thing being mutated ('subscriber', 'watchlist',
--                   'saved_view', 'subscription'). Optional; null for
--                   actions that don't have a clear target object.
--   entity_id     — id of the thing being mutated. Optional.
--   before        — JSONB snapshot of the relevant fields BEFORE the change
--                   (null for create actions)
--   after         — JSONB snapshot of the relevant fields AFTER the change
--                   (null for delete actions)
--   metadata      — JSONB blob for action-specific context (e.g.
--                   {"old_plan":"pro","new_plan":"team","stripe_event":"…"})
--   ip_address    — request IP (best-effort; null if unavailable)
--   user_agent    — request user-agent (best-effort; null if unavailable)
--   created_at    — when the action was performed (server time)
--
-- Append-only: rows are NEVER updated or deleted by application code. If a
-- compliance need ever requires PII redaction, do it via a separate
-- redaction process and log THAT redaction as another audit entry.

CREATE TABLE IF NOT EXISTS audit_log (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_email   TEXT NOT NULL,
  actor_id      TEXT,
  action        TEXT NOT NULL,
  entity_type   TEXT,
  entity_id     TEXT,
  before        JSONB,
  after         JSONB,
  metadata      JSONB,
  ip_address    INET,
  user_agent    TEXT,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Hot path: "show me everything user X did, most recent first"
CREATE INDEX IF NOT EXISTS idx_audit_actor_recent
  ON audit_log (actor_email, created_at DESC);

-- Hot path: "show me every {plan upgrade, account deletion} across the org"
CREATE INDEX IF NOT EXISTS idx_audit_action_recent
  ON audit_log (action, created_at DESC);

-- Hot path: time-window scans for compliance reports
CREATE INDEX IF NOT EXISTS idx_audit_created_at
  ON audit_log (created_at DESC);

-- ─── 0007_team_seats.sql ─────────────────────────────────────────────

-- 0007_team_seats.sql
--
-- Team seats infrastructure for the Team and Enterprise tiers.
--
-- Background: the pricing page advertises "up to 5 seats" on Team and
-- "unlimited seats" on Enterprise, but until now the product had no
-- concept of a team. This migration adds three things:
--
--   1. teams           — one row per organization on a Team/Enterprise sub
--   2. team_invites    — pending email invites (token-based)
--   3. subscribers.team_id + subscribers.team_role — membership + role
--
-- ── Membership model ─────────────────────────────────────────────────────
--   - One team per user (MVP). A subscriber row has at most one team_id.
--     Multi-team membership is a future migration if/when needed.
--   - Two roles: 'owner' | 'member'. Admin tier deferred — for now the
--     owner does invites/removals; members read.
--   - When a team owner leaves (rare; deferred), the team must be transferred
--     or deleted. Today the API blocks this; we'll add transfer in a follow-up.
--
-- ── Plan inheritance ─────────────────────────────────────────────────────
--   - Members inherit the team's plan (subscribers.plan tracks team.plan).
--   - Stripe webhook propagates plan changes from the owner's subscription
--     down to every team member.
--   - When a member leaves the team, their subscriber.plan reverts to 'free'.
--
-- ── Seat enforcement ─────────────────────────────────────────────────────
--   - Hard cap at teams.seat_limit (5 for Team, NULL = unlimited for
--     Enterprise). Enforced by the invite API, not in the DB — we want a
--     clean 'Seat limit reached' error, not a constraint violation.
--   - Pending invites count against the seat cap (so 4 active members + 1
--     pending = full).
--
-- ── Invite tokens ────────────────────────────────────────────────────────
--   - 32-byte URL-safe random token, generated server-side.
--   - 7-day expiry by default (configurable per-invite).
--   - Status transitions: pending → (accepted | cancelled | expired).
--   - Invites are NEVER deleted, just marked — preserves audit trail.

-- Teams table
CREATE TABLE IF NOT EXISTS teams (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                    TEXT NOT NULL,
  owner_id                TEXT NOT NULL,    -- subscriber_id of the owner
  plan                    TEXT NOT NULL DEFAULT 'team',  -- 'team' | 'enterprise'
  seat_limit              INTEGER,           -- NULL = unlimited (Enterprise)
  stripe_customer_id      TEXT,
  stripe_subscription_id  TEXT,
  created_at              TIMESTAMPTZ DEFAULT NOW(),
  updated_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_teams_owner ON teams (owner_id);
CREATE INDEX IF NOT EXISTS idx_teams_stripe_customer ON teams (stripe_customer_id) WHERE stripe_customer_id IS NOT NULL;

-- Team invites — token-based pending memberships
CREATE TABLE IF NOT EXISTS team_invites (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id       UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  email         TEXT NOT NULL,
  token         TEXT NOT NULL UNIQUE,
  invited_by    TEXT NOT NULL,    -- subscriber_id of the inviter
  status        TEXT NOT NULL DEFAULT 'pending',
  expires_at    TIMESTAMPTZ NOT NULL,
  accepted_at   TIMESTAMPTZ,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Hot path: token lookup on accept (filtered to pending so the partial
-- index stays compact even after thousands of accepted/cancelled rows).
CREATE INDEX IF NOT EXISTS idx_team_invites_token_pending
  ON team_invites (token) WHERE status = 'pending';

-- Hot path: "what teams has this email been invited to?" + dedup checks
CREATE INDEX IF NOT EXISTS idx_team_invites_email_status
  ON team_invites (email, status);

-- Hot path: list pending invites for a team (settings page)
CREATE INDEX IF NOT EXISTS idx_team_invites_team_status
  ON team_invites (team_id, status);

-- Subscribers gain team membership fields
ALTER TABLE subscribers
  ADD COLUMN IF NOT EXISTS team_id   UUID,
  ADD COLUMN IF NOT EXISTS team_role TEXT;  -- 'owner' | 'member'

CREATE INDEX IF NOT EXISTS idx_subscribers_team
  ON subscribers (team_id) WHERE team_id IS NOT NULL;

-- A subscriber should not have a team_role without a team_id, and vice versa.
-- We don't enforce this with a CHECK constraint at the DB level (it would
-- block partial state during the brief moment between assigning team_id
-- and team_role in a transaction), but the API guarantees it.

-- ─── 0008_team_watchlist.sql ─────────────────────────────────────────────

-- 0008_team_watchlist.sql
--
-- Team-wide shared watchlist (the second half of the Team-tier value prop).
--
-- Background: subscribers.watchlist_json already stores each user's personal
-- watchlist. The Team plan promised "shared watchlists across the team"
-- alongside the seat sharing shipped in 0007 — this migration adds the
-- team-side storage.
--
-- ── Storage shape ────────────────────────────────────────────────────────
-- JSONB array of uppercase ticker strings. Same shape as
-- subscribers.watchlist_json so the same readers/sanitizers work on both.
-- 50-entry cap enforced at the API layer (matches the 20-entry personal cap
-- but more generous since teams aggregate multiple users' interests).
--
-- ── Permission model ─────────────────────────────────────────────────────
-- Owner: read + write
-- Member: read-only
-- Enforced in lib/teams.setTeamWatchlist via canManageTeam().
--
-- ── UI presentation ──────────────────────────────────────────────────────
-- Personal and team lists are shown as two distinct sections (no
-- auto-merge in the UI). Daily email briefings DO union both lists when
-- computing watchlist activity, so a member sees both their personal
-- companies AND the team's companies in their morning brief.
--
-- ── Migration safety ─────────────────────────────────────────────────────
-- Idempotent ADD COLUMN IF NOT EXISTS. Default '[]'::jsonb so existing
-- teams immediately have a valid empty list. No backfill needed.

ALTER TABLE teams
  ADD COLUMN IF NOT EXISTS watchlist_json JSONB DEFAULT '[]'::jsonb NOT NULL;

-- ─── 0009_team_slack_webhook.sql ─────────────────────────────────────────────

-- 0009_team_slack_webhook.sql
--
-- Slack integration for the Team and Enterprise tiers.
--
-- Background: the pricing page advertises "Slack integration" as a Team
-- feature alongside seats and shared watchlist. This migration adds the
-- minimal storage required to wire it up.
--
-- ── Storage shape ────────────────────────────────────────────────────────
-- Single TEXT column on teams. Stores the raw Incoming Webhook URL,
-- which looks like:
--   https://hooks.slack.com/services/T0XXXXXXX/B0XXXXXXX/abcdefg…
-- The URL itself is the only secret — anyone holding it can post to the
-- channel. Supabase encrypts at rest; we never log it.
--
-- ── Why incoming webhooks (not OAuth) ────────────────────────────────────
-- Incoming webhooks need no app submission, no scopes, no token rotation.
-- The owner creates one in their Slack workspace settings (one-time, ~30s)
-- and pastes the URL. We POST JSON to it. Migration to a real Slack OAuth
-- app is a future PR if customers ask for DMs / multi-channel routing /
-- interactive buttons.
--
-- ── Permission model ─────────────────────────────────────────────────────
-- Only the team owner may set/clear the webhook. Members read-only.
-- Enforced in lib/teams.setTeamSlackWebhook via canManageTeam().
--
-- ── Validation ───────────────────────────────────────────────────────────
-- API enforces the URL must start with 'https://hooks.slack.com/services/'.
-- We do NOT validate against Slack's API on save (no OAuth means no token);
-- instead we offer a 'Send test message' button on the /team page that
-- POSTs immediately and reports success / 4xx back to the owner.
--
-- Migration is idempotent. No backfill needed.

ALTER TABLE teams
  ADD COLUMN IF NOT EXISTS slack_webhook_url TEXT;

-- ─── 0010_trial_drip.sql ─────────────────────────────────────────────

-- 0010_trial_drip.sql
--
-- Trial conversion email drip — schema additions.
--
-- Background: when a user starts a Pro trial via Stripe Checkout
-- (subscription_data[trial_period_days]=7), they currently get nothing
-- until day 7. The daily Pro briefing fires for them, but there's no
-- onboarding sequence walking them through the value. Industry baseline
-- says a 5-touch trial drip lifts trial → paid conversion 25-40%.
--
-- This migration adds the two columns the cron scheduler needs:
--
--   trial_started_at        — set by the Stripe webhook when the trial
--                              checkout completes. Cron uses NOW() -
--                              trial_started_at to compute "day N" of trial.
--   trial_emails_sent_json  — JSONB array of day-codes already sent
--                              (e.g. ["welcome","day1_brief","day3_calc"]).
--                              Idempotency: cron skips a day-code already in
--                              this array, so a missed day or a replay
--                              never double-sends.
--
-- ── Why a JSON array (not separate boolean columns) ─────────────────────
-- Two reasons:
--   1. Adding/removing email types in the drip becomes a code change, not
--      a schema migration.
--   2. The set is small (≤ 5 entries) so JSONB containment ops are O(1)
--      in practice. No index needed.
--
-- ── Cleanup ─────────────────────────────────────────────────────────────
-- We deliberately do NOT clear trial_emails_sent_json when the trial
-- ends. It serves as a permanent record of what the user received, which
-- helps debug any "why didn't I get email X?" support questions.
--
-- Migration is idempotent. No backfill needed — existing subscribers have
-- NULL trial_started_at and []::jsonb sent list, which means the cron
-- skips them entirely (no retroactive welcome emails to long-time users).

ALTER TABLE subscribers
  ADD COLUMN IF NOT EXISTS trial_started_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS trial_emails_sent_json JSONB DEFAULT '[]'::jsonb NOT NULL;

-- Hot path for the cron: "find every subscriber whose trial is in days 0-7"
-- Partial index keeps it small — most subscribers aren't in trial.
CREATE INDEX IF NOT EXISTS idx_subscribers_trial_started
  ON subscribers (trial_started_at)
  WHERE trial_started_at IS NOT NULL;
